defaults: &defaults
  working_directory: ~/src
  docker:
    - image: circleci/node:8.9.1

version: 2
jobs:
  test:
    <<: *defaults
    steps:
      - checkout
      - run: echo 'export PATH=$HOME/src/node_modules/.bin:$PATH' >> $BASH_ENV
      - run: yarn
      - run: yarn test
      - store_artifacts:
          path: test-results.xml
          prefix: tests
      - store_artifacts:
          path: coverage
          prefix: coverage
      - store_test_results:
          path: test-results.xml

  deploy-branch:
    <<: *defaults
    steps:
      - checkout
      - run: yarn add global now
      - setup_remote_docker
      - run: echo 'export PATH=$HOME/src/node_modules/.bin:$PATH' >> $BASH_ENV
      - run: |
          docker run --name the-sim stephengfriend/the-sim
      - run: |
          docker cp the-sim:/src/output/latest.json "$HOME"/src/latest.json
      - run: URL=$(now --public -t $NOW_TOKEN)
      - run: now -t $NOW_TOKEN alias set $URL $CIRCLE_BRANCH-the-sim-api
      - run: now -t $NOW_TOKEN rm --safe -y $CIRCLE_BRANCH-the-sim-api
  deploy-master:
    <<: *defaults
    steps:
      - checkout
      - run: yarn add global now
      - setup_remote_docker
      - run: echo 'export PATH=$HOME/src/node_modules/.bin:$PATH' >> $BASH_ENV
      - run: |
          docker run --name the-sim stephengfriend/the-sim
      - run: |
          docker cp the-sim:/src/output/latest.json "$HOME"/src/latest.json
      - run: now --public -t $NOW_TOKEN
      - run: now -t $NOW_TOKEN alias the-sim-api
      - run: now -t $NOW_TOKEN rm --safe -y the-sim-api

workflows:
  version: 2
  commit:
    jobs:
      - test
      - deploy-branch:
          requires:
            - test
          filters:
            branches:
              only: /^(?!master$).*$/
      - deploy-master:
          requires:
            - test
          filters:
            branches:
              only: master
  nightly:
    triggers:
      - schedule:
          cron: "0 4,10,16,22 * * *" # UTC
          filters:
            branches:
              only:
                - master
    jobs:
      - deploy-master
